/* Generated by scripts/generate-first-service-browser-inventory.ts. Do not edit. */
export const FIRST_SERVICE_BROWSER_INVENTORY = Object.freeze({
  "contentVersion": "phase-1-evening-service-v1",
  "reviewIds": [
    "phase-1-service-review-pending-v1"
  ],
  "copyRefs": [
    "action.presentation.indigo-rim",
    "action.presentation.sand-speckle",
    "action.restoration.mend-counter-stool",
    "action.restoration.polish-display-shelf",
    "action.restoration.refresh-menu-board",
    "action.service.abandon",
    "cue.abandon.invalid",
    "cue.ledger.orders-incomplete",
    "cue.order.accept.ceramicist-kappa",
    "cue.order.accept.courier-salmon",
    "cue.order.accept.fishmonger-tamago",
    "cue.order.expected.ceramicist-kappa",
    "cue.order.expected.courier-salmon",
    "cue.order.expected.fishmonger-tamago",
    "cue.orders.complete",
    "cue.orders.served",
    "cue.plate.required.ceramicist-kappa",
    "cue.plate.required.courier-salmon",
    "cue.plate.required.fishmonger-tamago",
    "cue.presentation.invalid",
    "cue.restoration.invalid",
    "cue.rice.complete",
    "cue.rice.expected.season",
    "cue.rice.expected.steam",
    "cue.rice.expected.wash",
    "cue.serve.required.ceramicist-kappa",
    "cue.serve.required.courier-salmon",
    "cue.serve.required.fishmonger-tamago",
    "cue.service.complete",
    "cue.start.invalid",
    "cue.step.ceramicist-kappa.cut-kappa",
    "cue.step.ceramicist-kappa.layer-nori",
    "cue.step.ceramicist-kappa.place-cucumber",
    "cue.step.ceramicist-kappa.portion-rice",
    "cue.step.ceramicist-kappa.roll-kappa",
    "cue.step.courier-salmon.arrange-salmon",
    "cue.step.courier-salmon.place-salmon",
    "cue.step.courier-salmon.portion-rice",
    "cue.step.courier-salmon.press-rice",
    "cue.step.fishmonger-tamago.bind-tamago",
    "cue.step.fishmonger-tamago.place-tamago",
    "cue.step.fishmonger-tamago.portion-rice",
    "cue.step.fishmonger-tamago.press-rice",
    "dish.kappa-maki",
    "dish.salmon-nigiri",
    "dish.tamago-nigiri",
    "feedback.ledger.closed",
    "feedback.plate.ceramicist-kappa",
    "feedback.plate.courier-salmon",
    "feedback.plate.fishmonger-tamago",
    "feedback.presentation.indigo-rim",
    "feedback.presentation.sand-speckle",
    "feedback.rice.season.saved",
    "feedback.rice.steam.saved",
    "feedback.rice.wash.saved",
    "feedback.serve.ceramicist-kappa",
    "feedback.serve.courier-salmon",
    "feedback.serve.fishmonger-tamago",
    "feedback.service.abandoned",
    "feedback.service.opened",
    "feedback.service.settled",
    "guest.ceramicist",
    "guest.ceramicist.dialogue",
    "guest.courier",
    "guest.courier.dialogue",
    "guest.fishmonger",
    "guest.fishmonger.dialogue",
    "ledger.first-evening",
    "order-state.accepted",
    "order-state.discarded",
    "order-state.offered",
    "order-state.plated",
    "order-state.preparing",
    "order-state.ready-to-plate",
    "order-state.served",
    "outcome.content",
    "outcome.delighted",
    "outcome.recoverable-concern",
    "phase.abandoned",
    "phase.closing",
    "phase.idle",
    "phase.open",
    "phase.settled",
    "presentation.indigo-rim",
    "presentation.sand-speckle",
    "prompt.ledger.close",
    "prompt.order.accept.ceramicist-kappa",
    "prompt.order.accept.courier-salmon",
    "prompt.order.accept.fishmonger-tamago",
    "prompt.plate.ceramicist-kappa",
    "prompt.plate.courier-salmon",
    "prompt.plate.fishmonger-tamago",
    "prompt.presentation.choose",
    "prompt.restoration.choose",
    "prompt.rice.season",
    "prompt.rice.steam",
    "prompt.rice.wash",
    "prompt.serve.ceramicist-kappa",
    "prompt.serve.courier-salmon",
    "prompt.serve.fishmonger-tamago",
    "prompt.service.abandoned",
    "prompt.service.settled",
    "prompt.service.start",
    "prompt.step.ceramicist-kappa.cut-kappa",
    "prompt.step.ceramicist-kappa.layer-nori",
    "prompt.step.ceramicist-kappa.place-cucumber",
    "prompt.step.ceramicist-kappa.portion-rice",
    "prompt.step.ceramicist-kappa.roll-kappa",
    "prompt.step.courier-salmon.arrange-salmon",
    "prompt.step.courier-salmon.place-salmon",
    "prompt.step.courier-salmon.portion-rice",
    "prompt.step.courier-salmon.press-rice",
    "prompt.step.fishmonger-tamago.bind-tamago",
    "prompt.step.fishmonger-tamago.place-tamago",
    "prompt.step.fishmonger-tamago.portion-rice",
    "prompt.step.fishmonger-tamago.press-rice",
    "restoration.mend-counter-stool",
    "restoration.polish-display-shelf",
    "restoration.refresh-menu-board",
    "rice.season",
    "rice.steam",
    "rice.wash",
    "service.first-evening",
    "station.nigiri-counter",
    "station.prep-sashimi-board",
    "station.rice-hearth",
    "station.rolling-mat",
    "story-flag.ceramicist-first-service-served",
    "story-flag.courier-first-service-served",
    "story-flag.fishmonger-first-service-served",
    "story.ceramicist.first-service",
    "story.courier.first-service",
    "story.fishmonger.first-service",
    "unlock.atlantic-salmon-sashimi@1"
  ],
  "copy": {
    "action.presentation.indigo-rim": {
      "text": "Use the double-rim plate",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "action.presentation.sand-speckle": {
      "text": "Use the speckled-field plate",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "action.restoration.mend-counter-stool": {
      "text": "Mend the counter stool",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "action.restoration.polish-display-shelf": {
      "text": "Polish the display shelf",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "action.restoration.refresh-menu-board": {
      "text": "Refresh the menu board",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "action.service.abandon": {
      "text": "End shift early",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "cue.abandon.invalid": {
      "text": "Open the counter before ending a shift.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "cue.ledger.orders-incomplete": {
      "text": "Serve all three authored orders before closing the ledger.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "cue.order.accept.ceramicist-kappa": {
      "text": "Accept the ceramicist's kappa maki order next.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "cue.order.accept.courier-salmon": {
      "text": "Accept the courier's salmon nigiri order next.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "cue.order.accept.fishmonger-tamago": {
      "text": "Accept the fishmonger's tamago nigiri order next.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "cue.order.expected.ceramicist-kappa": {
      "text": "Continue the ceramicist's kappa maki order.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "cue.order.expected.courier-salmon": {
      "text": "Continue the courier's salmon nigiri order.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "cue.order.expected.fishmonger-tamago": {
      "text": "Continue the fishmonger's tamago nigiri order.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "cue.orders.complete": {
      "text": "Every authored order is complete.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "cue.orders.served": {
      "text": "Every authored order is served.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "cue.plate.required.ceramicist-kappa": {
      "text": "Complete and plate the kappa maki before serving.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "cue.plate.required.courier-salmon": {
      "text": "Complete and plate the salmon nigiri before serving.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "cue.plate.required.fishmonger-tamago": {
      "text": "Complete and plate the tamago nigiri before serving.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "cue.presentation.invalid": {
      "text": "Choose one available cosmetic presentation for the first plate.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "cue.restoration.invalid": {
      "text": "Choose one available cosmetic restoration after closing the ledger.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "cue.rice.complete": {
      "text": "The three rice preparation beats are already complete.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "cue.rice.expected.season": {
      "text": "Season is the next forgiving rice preparation beat.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "cue.rice.expected.steam": {
      "text": "Steam is the next forgiving rice preparation beat.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "cue.rice.expected.wash": {
      "text": "Wash is the next forgiving rice preparation beat.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "cue.serve.required.ceramicist-kappa": {
      "text": "Plate the kappa maki before serving it.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "cue.serve.required.courier-salmon": {
      "text": "Plate the salmon nigiri before serving it.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "cue.serve.required.fishmonger-tamago": {
      "text": "Plate the tamago nigiri before serving it.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "cue.service.complete": {
      "text": "This service is already complete.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "cue.start.invalid": {
      "text": "Open the service only from the idle ledger.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "cue.step.ceramicist-kappa.cut-kappa": {
      "text": "Cut the completed roll only after rolling it.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "cue.step.ceramicist-kappa.layer-nori": {
      "text": "Layer nori on the rolling mat first.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "cue.step.ceramicist-kappa.place-cucumber": {
      "text": "Place cucumber after the rice.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "cue.step.ceramicist-kappa.portion-rice": {
      "text": "Portion prepared sushi rice over the nori.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "cue.step.ceramicist-kappa.roll-kappa": {
      "text": "Roll after nori, rice, and cucumber are aligned.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "cue.step.courier-salmon.arrange-salmon": {
      "text": "Arrange the authored salmon topping at the prep board first.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "cue.step.courier-salmon.place-salmon": {
      "text": "Place the authored salmon topping after shaping the rice.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "cue.step.courier-salmon.portion-rice": {
      "text": "Portion prepared sushi rice at the nigiri counter.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "cue.step.courier-salmon.press-rice": {
      "text": "Press the portioned rice before adding the topping.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "cue.step.fishmonger-tamago.bind-tamago": {
      "text": "Bind the tamago only after placing it.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "cue.step.fishmonger-tamago.place-tamago": {
      "text": "Place the cooked tamago after shaping the rice.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "cue.step.fishmonger-tamago.portion-rice": {
      "text": "Portion prepared sushi rice at the nigiri counter.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "cue.step.fishmonger-tamago.press-rice": {
      "text": "Press the portioned rice before adding the topping.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "dish.kappa-maki": {
      "text": "Kappa maki",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "dish.salmon-nigiri": {
      "text": "Salmon nigiri",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "dish.tamago-nigiri": {
      "text": "Tamago nigiri",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "feedback.ledger.closed": {
      "text": "The evening ledger is closed.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "feedback.plate.ceramicist-kappa": {
      "text": "The ceramicist notices the clean, even roll.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "feedback.plate.courier-salmon": {
      "text": "The courier sees the final plate arrive complete.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "feedback.plate.fishmonger-tamago": {
      "text": "The fishmonger sees the tamago held neatly in place.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "feedback.presentation.indigo-rim": {
      "text": "The double-rim plate is saved as the cosmetic presentation.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "feedback.presentation.sand-speckle": {
      "text": "The speckled-field plate is saved as the cosmetic presentation.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "feedback.rice.season.saved": {
      "text": "The seasoning beat is saved.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "feedback.rice.steam.saved": {
      "text": "The steaming beat is saved.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "feedback.rice.wash.saved": {
      "text": "The washing beat is saved.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "feedback.serve.ceramicist-kappa": {
      "text": "The ceramicist accepts the kappa maki with a quiet nod.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "feedback.serve.courier-salmon": {
      "text": "The courier accepts the salmon nigiri; every order in the ledger is now served.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "feedback.serve.fishmonger-tamago": {
      "text": "The fishmonger accepts the tamago nigiri and leaves the counter ready for the courier.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "feedback.service.abandoned": {
      "text": "Shift closed early without settlement or unlocks.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "feedback.service.opened": {
      "text": "The counter is open for the first service.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "feedback.service.settled": {
      "text": "The counter is restored and salmon sashimi is now available.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "guest.ceramicist": {
      "text": "The ceramicist",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "guest.ceramicist.dialogue": {
      "text": "The ceramicist asks for the authored cucumber roll.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "guest.courier": {
      "text": "The courier",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "guest.courier.dialogue": {
      "text": "The courier asks for the authored salmon nigiri.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "guest.fishmonger": {
      "text": "The fishmonger",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "guest.fishmonger.dialogue": {
      "text": "The fishmonger asks for the authored cooked-egg nigiri.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "ledger.first-evening": {
      "text": "First evening ledger",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "order-state.accepted": {
      "text": "Accepted",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "order-state.discarded": {
      "text": "Closed early",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "order-state.offered": {
      "text": "Waiting",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "order-state.plated": {
      "text": "Plated",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "order-state.preparing": {
      "text": "Preparing",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "order-state.ready-to-plate": {
      "text": "Ready to plate",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "order-state.served": {
      "text": "Served",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "outcome.content": {
      "text": "Content",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "outcome.delighted": {
      "text": "Delighted",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "outcome.recoverable-concern": {
      "text": "Recoverable concern",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "phase.abandoned": {
      "text": "Shift closed early.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "phase.closing": {
      "text": "Close the evening ledger.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "phase.idle": {
      "text": "Your counter opens tonight.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "phase.open": {
      "text": "The counter is open.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "phase.settled": {
      "text": "Counter closed. Tonight's service is saved.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "presentation.indigo-rim": {
      "text": "Double-rim plate",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "presentation.sand-speckle": {
      "text": "Speckled-field plate",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "prompt.ledger.close": {
      "text": "Close the ledger after all three orders are served.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "prompt.order.accept.ceramicist-kappa": {
      "text": "Accept the ceramicist's kappa maki order.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "prompt.order.accept.courier-salmon": {
      "text": "Accept the courier's salmon nigiri order.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "prompt.order.accept.fishmonger-tamago": {
      "text": "Accept the fishmonger's tamago nigiri order.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "prompt.plate.ceramicist-kappa": {
      "text": "Plate the kappa maki.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "prompt.plate.courier-salmon": {
      "text": "Plate the salmon nigiri.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "prompt.plate.fishmonger-tamago": {
      "text": "Plate the tamago nigiri.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "prompt.presentation.choose": {
      "text": "Choose one cosmetic presentation for the first plate.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "prompt.restoration.choose": {
      "text": "Choose one cosmetic restoration.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "prompt.rice.season": {
      "text": "Season the prepared rice.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "prompt.rice.steam": {
      "text": "Steam the washed rice.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "prompt.rice.wash": {
      "text": "Wash the rice.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "prompt.serve.ceramicist-kappa": {
      "text": "Serve the kappa maki.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "prompt.serve.courier-salmon": {
      "text": "Serve the salmon nigiri.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "prompt.serve.fishmonger-tamago": {
      "text": "Serve the tamago nigiri.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "prompt.service.abandoned": {
      "text": "Shift closed early.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "prompt.service.settled": {
      "text": "Counter closed. Tonight's service is saved.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "prompt.service.start": {
      "text": "Start the first shift.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "prompt.step.ceramicist-kappa.cut-kappa": {
      "text": "Cut the rolled kappa maki.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "prompt.step.ceramicist-kappa.layer-nori": {
      "text": "Layer nori on the rolling mat.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "prompt.step.ceramicist-kappa.place-cucumber": {
      "text": "Place cucumber along the center.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "prompt.step.ceramicist-kappa.portion-rice": {
      "text": "Portion prepared sushi rice over the nori.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "prompt.step.ceramicist-kappa.roll-kappa": {
      "text": "Roll the aligned kappa maki.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "prompt.step.courier-salmon.arrange-salmon": {
      "text": "Arrange the authored salmon topping at the prep board.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "prompt.step.courier-salmon.place-salmon": {
      "text": "Place the authored salmon topping over the rice.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "prompt.step.courier-salmon.portion-rice": {
      "text": "Portion prepared sushi rice at the nigiri counter.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "prompt.step.courier-salmon.press-rice": {
      "text": "Press the rice into its authored nigiri shape.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "prompt.step.fishmonger-tamago.bind-tamago": {
      "text": "Bind the tamago and rice with nori.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "prompt.step.fishmonger-tamago.place-tamago": {
      "text": "Place the cooked tamago over the rice.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "prompt.step.fishmonger-tamago.portion-rice": {
      "text": "Portion prepared sushi rice at the nigiri counter.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "prompt.step.fishmonger-tamago.press-rice": {
      "text": "Press the rice into its authored nigiri shape.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "restoration.mend-counter-stool": {
      "text": "Mend the counter stool",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "restoration.polish-display-shelf": {
      "text": "Polish the display shelf",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "restoration.refresh-menu-board": {
      "text": "Refresh the menu board",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "rice.season": {
      "text": "Seasoned rice",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "rice.steam": {
      "text": "Steamed rice",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "rice.wash": {
      "text": "Washed rice",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "service.first-evening": {
      "text": "First evening service",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "station.nigiri-counter": {
      "text": "Nigiri counter",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "station.prep-sashimi-board": {
      "text": "Prep and sashimi board",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "station.rice-hearth": {
      "text": "Rice hearth",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "station.rolling-mat": {
      "text": "Rolling mat",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "story-flag.ceramicist-first-service-served": {
      "text": "Ceramicist first-service order served",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "story-flag.courier-first-service-served": {
      "text": "Courier first-service order served",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "story-flag.fishmonger-first-service-served": {
      "text": "Fishmonger first-service order served",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "story.ceramicist.first-service": {
      "text": "The ceramicist remembers the neatly served first plate.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "story.courier.first-service": {
      "text": "The courier remembers that the counter completed the evening ledger.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "story.fishmonger.first-service": {
      "text": "The fishmonger remembers the carefully bound tamago nigiri.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "unlock.atlantic-salmon-sashimi@1": {
      "text": "Salmon sashimi unlocked: a rice-free preparation.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    }
  },
  "assetDimensions": {
    "counter-curtain-closed": [
      320,
      180
    ],
    "counter-curtain-open": [
      320,
      180
    ],
    "counter-lamp-lit": [
      64,
      64
    ],
    "dish-kappa-maki": [
      48,
      48
    ],
    "dish-kappa-maki-build": [
      48,
      48
    ],
    "dish-kappa-maki-plated": [
      64,
      48
    ],
    "dish-salmon-nigiri": [
      48,
      48
    ],
    "dish-salmon-nigiri-build": [
      48,
      48
    ],
    "dish-salmon-nigiri-plated": [
      64,
      48
    ],
    "dish-salmon-sashimi": [
      48,
      48
    ],
    "dish-salmon-sashimi-locked": [
      48,
      48
    ],
    "dish-tamago-nigiri": [
      48,
      48
    ],
    "dish-tamago-nigiri-build": [
      48,
      48
    ],
    "dish-tamago-nigiri-plated": [
      64,
      48
    ],
    "guest-ceramicist-content": [
      32,
      48
    ],
    "guest-ceramicist-delighted": [
      32,
      48
    ],
    "guest-ceramicist-neutral": [
      32,
      48
    ],
    "guest-ceramicist-recoverable": [
      32,
      48
    ],
    "guest-courier-content": [
      32,
      48
    ],
    "guest-courier-delighted": [
      32,
      48
    ],
    "guest-courier-neutral": [
      32,
      48
    ],
    "guest-courier-recoverable": [
      32,
      48
    ],
    "guest-fishmonger-content": [
      32,
      48
    ],
    "guest-fishmonger-delighted": [
      32,
      48
    ],
    "guest-fishmonger-neutral": [
      32,
      48
    ],
    "guest-fishmonger-recoverable": [
      32,
      48
    ],
    "ingredient-cucumber": [
      24,
      24
    ],
    "ingredient-nori": [
      24,
      24
    ],
    "ingredient-salmon": [
      24,
      24
    ],
    "ingredient-sushi-rice": [
      24,
      24
    ],
    "ingredient-tamago": [
      24,
      24
    ],
    "ingredient-vinegar": [
      24,
      24
    ],
    "presentation-indigo-rim": [
      64,
      32
    ],
    "presentation-sand-speckle": [
      64,
      32
    ],
    "restoration-counter-stool": [
      64,
      64
    ],
    "restoration-display-shelf": [
      64,
      64
    ],
    "restoration-menu-board": [
      64,
      64
    ],
    "rice-cooked": [
      32,
      32
    ],
    "rice-seasoned": [
      32,
      32
    ],
    "rice-washed": [
      32,
      32
    ],
    "station-nigiri-counter": [
      24,
      24
    ],
    "station-prep-board": [
      24,
      24
    ],
    "station-rice-hearth": [
      24,
      24
    ],
    "station-rolling-mat": [
      24,
      24
    ]
  },
  "assets": {
    "counter-curtain-closed": {
      "path": "/service-assets/first-service.svg#counter-curtain-closed",
      "width": 320,
      "height": 180,
      "nonColorIdentity": "A closed curtain silhouette with a plainly labeled counter threshold.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "counter-curtain-open": {
      "path": "/service-assets/first-service.svg#counter-curtain-open",
      "width": 320,
      "height": 180,
      "nonColorIdentity": "An open curtain silhouette with the same counter geometry.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "counter-lamp-lit": {
      "path": "/service-assets/first-service.svg#counter-lamp-lit",
      "width": 64,
      "height": 64,
      "nonColorIdentity": "A lit counter lamp with a distinct radiant outline.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "dish-kappa-maki": {
      "path": "/service-assets/first-service.svg#dish-kappa-maki",
      "width": 48,
      "height": 48,
      "nonColorIdentity": "A sliced cucumber roll with an outer nori ring.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "dish-kappa-maki-build": {
      "path": "/service-assets/first-service.svg#dish-kappa-maki-build",
      "width": 48,
      "height": 48,
      "nonColorIdentity": "Layered nori, rice, and cucumber build silhouette.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "dish-kappa-maki-plated": {
      "path": "/service-assets/first-service.svg#dish-kappa-maki-plated",
      "width": 64,
      "height": 48,
      "nonColorIdentity": "The sliced cucumber roll centered on a plainly outlined plate.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "dish-salmon-nigiri": {
      "path": "/service-assets/first-service.svg#dish-salmon-nigiri",
      "width": 48,
      "height": 48,
      "nonColorIdentity": "A broad salmon topping over a compact rice base.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "dish-salmon-nigiri-build": {
      "path": "/service-assets/first-service.svg#dish-salmon-nigiri-build",
      "width": 48,
      "height": 48,
      "nonColorIdentity": "Layered broad salmon topping and compact rice build silhouette.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "dish-salmon-nigiri-plated": {
      "path": "/service-assets/first-service.svg#dish-salmon-nigiri-plated",
      "width": 64,
      "height": 48,
      "nonColorIdentity": "The salmon nigiri centered on a plainly outlined plate.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "dish-salmon-sashimi": {
      "path": "/service-assets/first-service.svg#dish-salmon-sashimi",
      "width": 48,
      "height": 48,
      "nonColorIdentity": "Three rice-free broad salmon slices in a staggered fan.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "dish-salmon-sashimi-locked": {
      "path": "/service-assets/first-service.svg#dish-salmon-sashimi-locked",
      "width": 48,
      "height": 48,
      "nonColorIdentity": "A locked tile around a rice-free three-slice silhouette.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "dish-tamago-nigiri": {
      "path": "/service-assets/first-service.svg#dish-tamago-nigiri",
      "width": 48,
      "height": 48,
      "nonColorIdentity": "A rectangular cooked egg topping bound to rice by a center nori strip.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "dish-tamago-nigiri-build": {
      "path": "/service-assets/first-service.svg#dish-tamago-nigiri-build",
      "width": 48,
      "height": 48,
      "nonColorIdentity": "Layered rectangular egg, center binding, and rice build silhouette.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "dish-tamago-nigiri-plated": {
      "path": "/service-assets/first-service.svg#dish-tamago-nigiri-plated",
      "width": 64,
      "height": 48,
      "nonColorIdentity": "The tamago nigiri centered on a plainly outlined plate.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "guest-ceramicist-content": {
      "path": "/service-assets/first-service.svg#guest-ceramicist-content",
      "width": 32,
      "height": 48,
      "nonColorIdentity": "Ceramicist role portrait with a relaxed open-hand silhouette.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "guest-ceramicist-delighted": {
      "path": "/service-assets/first-service.svg#guest-ceramicist-delighted",
      "width": 32,
      "height": 48,
      "nonColorIdentity": "Ceramicist role portrait with an upright open-hand silhouette.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "guest-ceramicist-neutral": {
      "path": "/service-assets/first-service.svg#guest-ceramicist-neutral",
      "width": 32,
      "height": 48,
      "nonColorIdentity": "Ceramicist role portrait with a relaxed closed-hand silhouette.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "guest-ceramicist-recoverable": {
      "path": "/service-assets/first-service.svg#guest-ceramicist-recoverable",
      "width": 32,
      "height": 48,
      "nonColorIdentity": "Ceramicist role portrait with a plainly marked concern bubble.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "guest-courier-content": {
      "path": "/service-assets/first-service.svg#guest-courier-content",
      "width": 32,
      "height": 48,
      "nonColorIdentity": "Courier role portrait with parcel held at the side.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "guest-courier-delighted": {
      "path": "/service-assets/first-service.svg#guest-courier-delighted",
      "width": 32,
      "height": 48,
      "nonColorIdentity": "Courier role portrait with parcel lifted once.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "guest-courier-neutral": {
      "path": "/service-assets/first-service.svg#guest-courier-neutral",
      "width": 32,
      "height": 48,
      "nonColorIdentity": "Courier role portrait with parcel centered.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "guest-courier-recoverable": {
      "path": "/service-assets/first-service.svg#guest-courier-recoverable",
      "width": 32,
      "height": 48,
      "nonColorIdentity": "Courier role portrait with a plainly marked concern bubble.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "guest-fishmonger-content": {
      "path": "/service-assets/first-service.svg#guest-fishmonger-content",
      "width": 32,
      "height": 48,
      "nonColorIdentity": "Fishmonger role portrait with apron panel relaxed.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "guest-fishmonger-delighted": {
      "path": "/service-assets/first-service.svg#guest-fishmonger-delighted",
      "width": 32,
      "height": 48,
      "nonColorIdentity": "Fishmonger role portrait with apron panel and open hands.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "guest-fishmonger-neutral": {
      "path": "/service-assets/first-service.svg#guest-fishmonger-neutral",
      "width": 32,
      "height": 48,
      "nonColorIdentity": "Fishmonger role portrait with apron panel centered.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "guest-fishmonger-recoverable": {
      "path": "/service-assets/first-service.svg#guest-fishmonger-recoverable",
      "width": 32,
      "height": 48,
      "nonColorIdentity": "Fishmonger role portrait with a plainly marked concern bubble.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "ingredient-cucumber": {
      "path": "/service-assets/first-service.svg#ingredient-cucumber",
      "width": 24,
      "height": 24,
      "nonColorIdentity": "A long cut cucumber silhouette.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "ingredient-nori": {
      "path": "/service-assets/first-service.svg#ingredient-nori",
      "width": 24,
      "height": 24,
      "nonColorIdentity": "A square sheet silhouette with a corner notch.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "ingredient-salmon": {
      "path": "/service-assets/first-service.svg#ingredient-salmon",
      "width": 24,
      "height": 24,
      "nonColorIdentity": "A broad prepared salmon component silhouette.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "ingredient-sushi-rice": {
      "path": "/service-assets/first-service.svg#ingredient-sushi-rice",
      "width": 24,
      "height": 24,
      "nonColorIdentity": "A compact rice mound silhouette.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "ingredient-tamago": {
      "path": "/service-assets/first-service.svg#ingredient-tamago",
      "width": 24,
      "height": 24,
      "nonColorIdentity": "A rectangular cooked egg silhouette.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "ingredient-vinegar": {
      "path": "/service-assets/first-service.svg#ingredient-vinegar",
      "width": 24,
      "height": 24,
      "nonColorIdentity": "A narrow labeled seasoning vessel silhouette.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "presentation-indigo-rim": {
      "path": "/service-assets/first-service.svg#presentation-indigo-rim",
      "width": 64,
      "height": 32,
      "nonColorIdentity": "A plate backplate identified by a double rim, not color alone.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "presentation-sand-speckle": {
      "path": "/service-assets/first-service.svg#presentation-sand-speckle",
      "width": 64,
      "height": 32,
      "nonColorIdentity": "A plate backplate identified by a speckled field, not color alone.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "restoration-counter-stool": {
      "path": "/service-assets/first-service.svg#restoration-counter-stool",
      "width": 64,
      "height": 64,
      "nonColorIdentity": "A repaired counter stool overlay.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "restoration-display-shelf": {
      "path": "/service-assets/first-service.svg#restoration-display-shelf",
      "width": 64,
      "height": 64,
      "nonColorIdentity": "A polished display shelf overlay.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "restoration-menu-board": {
      "path": "/service-assets/first-service.svg#restoration-menu-board",
      "width": 64,
      "height": 64,
      "nonColorIdentity": "A refreshed menu board overlay with no invented script.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "rice-cooked": {
      "path": "/service-assets/first-service.svg#rice-cooked",
      "width": 32,
      "height": 32,
      "nonColorIdentity": "A cooked rice silhouette with a rounded steam marker.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "rice-seasoned": {
      "path": "/service-assets/first-service.svg#rice-seasoned",
      "width": 32,
      "height": 32,
      "nonColorIdentity": "A seasoned rice silhouette with a mixing paddle marker.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "rice-washed": {
      "path": "/service-assets/first-service.svg#rice-washed",
      "width": 32,
      "height": 32,
      "nonColorIdentity": "A washed rice silhouette with a water-line marker.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "station-nigiri-counter": {
      "path": "/service-assets/first-service.svg#station-nigiri-counter",
      "width": 24,
      "height": 24,
      "nonColorIdentity": "A low shaping counter glyph.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "station-prep-board": {
      "path": "/service-assets/first-service.svg#station-prep-board",
      "width": 24,
      "height": 24,
      "nonColorIdentity": "A rectangular preparation board glyph.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "station-rice-hearth": {
      "path": "/service-assets/first-service.svg#station-rice-hearth",
      "width": 24,
      "height": 24,
      "nonColorIdentity": "A lidded rice vessel and hearth glyph.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    },
    "station-rolling-mat": {
      "path": "/service-assets/first-service.svg#station-rolling-mat",
      "width": 24,
      "height": 24,
      "nonColorIdentity": "A parallel-slat rolling mat glyph.",
      "reviewId": "phase-1-service-review-pending-v1",
      "reviewStatus": "review-pending"
    }
  },
  "sceneAnchors": {
    "counter-lamp-lit": [
      232,
      12
    ],
    "restoration-counter-stool": [
      24,
      100
    ],
    "restoration-display-shelf": [
      128,
      76
    ],
    "restoration-menu-board": [
      224,
      72
    ]
  },
  "orderStatusRefs": [
    "order-state.offered",
    "order-state.accepted",
    "order-state.preparing",
    "order-state.ready-to-plate",
    "order-state.plated",
    "order-state.served",
    "order-state.discarded"
  ],
  "orderIds": [
    "ceramicist-kappa",
    "fishmonger-tamago",
    "courier-salmon"
  ],
  "orderBindings": {
    "ceramicist-kappa": {
      "guestRef": "guest.ceramicist",
      "dishRef": "dish.kappa-maki"
    },
    "fishmonger-tamago": {
      "guestRef": "guest.fishmonger",
      "dishRef": "dish.tamago-nigiri"
    },
    "courier-salmon": {
      "guestRef": "guest.courier",
      "dishRef": "dish.salmon-nigiri"
    }
  },
  "commandNames": [
    "service.start",
    "service.prepare-rice",
    "service.accept-order",
    "service.perform-step",
    "service.choose-presentation",
    "service.plate-order",
    "service.serve-order",
    "service.close-ledger",
    "service.choose-restoration",
    "service.abandon"
  ],
  "riceBeats": [
    "wash",
    "steam",
    "season"
  ],
  "presentationChoices": [
    "indigo-rim",
    "sand-speckle"
  ],
  "restorationChoices": [
    "mend-counter-stool",
    "polish-display-shelf",
    "refresh-menu-board"
  ],
  "steps": {
    "ceramicist-kappa": [
      "layer-nori",
      "portion-rice",
      "place-cucumber",
      "roll-kappa",
      "cut-kappa"
    ],
    "fishmonger-tamago": [
      "portion-rice",
      "press-rice",
      "place-tamago",
      "bind-tamago"
    ],
    "courier-salmon": [
      "arrange-salmon",
      "portion-rice",
      "press-rice",
      "place-salmon"
    ]
  },
  "promptCommands": {
    "prompt.service.start": "service.start",
    "prompt.rice.wash": "service.prepare-rice",
    "prompt.rice.steam": "service.prepare-rice",
    "prompt.rice.season": "service.prepare-rice",
    "prompt.order.accept.ceramicist-kappa": "service.accept-order",
    "prompt.step.ceramicist-kappa.layer-nori": "service.perform-step",
    "prompt.step.ceramicist-kappa.portion-rice": "service.perform-step",
    "prompt.step.ceramicist-kappa.place-cucumber": "service.perform-step",
    "prompt.step.ceramicist-kappa.roll-kappa": "service.perform-step",
    "prompt.step.ceramicist-kappa.cut-kappa": "service.perform-step",
    "prompt.plate.ceramicist-kappa": "service.plate-order",
    "prompt.serve.ceramicist-kappa": "service.serve-order",
    "prompt.order.accept.fishmonger-tamago": "service.accept-order",
    "prompt.step.fishmonger-tamago.portion-rice": "service.perform-step",
    "prompt.step.fishmonger-tamago.press-rice": "service.perform-step",
    "prompt.step.fishmonger-tamago.place-tamago": "service.perform-step",
    "prompt.step.fishmonger-tamago.bind-tamago": "service.perform-step",
    "prompt.plate.fishmonger-tamago": "service.plate-order",
    "prompt.serve.fishmonger-tamago": "service.serve-order",
    "prompt.order.accept.courier-salmon": "service.accept-order",
    "prompt.step.courier-salmon.arrange-salmon": "service.perform-step",
    "prompt.step.courier-salmon.portion-rice": "service.perform-step",
    "prompt.step.courier-salmon.press-rice": "service.perform-step",
    "prompt.step.courier-salmon.place-salmon": "service.perform-step",
    "prompt.plate.courier-salmon": "service.plate-order",
    "prompt.serve.courier-salmon": "service.serve-order",
    "prompt.presentation.choose": "service.choose-presentation",
    "prompt.ledger.close": "service.close-ledger",
    "prompt.restoration.choose": "service.choose-restoration"
  }
} as const);
