import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import { copyFileSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, relative, resolve } from "node:path";
import { canonicalJson } from "../packages/domain/src/index";
import {
  FORBIDDEN_CONTRACT_SURFACE,
  RECEIPT_AUTHORITY_MANIFEST,
  RECEIPT_AUTHORITY_MANIFEST_HASH,
  parseSourceCandidateDeploymentManifest,
  sha256CanonicalJson,
} from "../packages/receipt-authority/src/deployment-manifest";
import {
  PUBLIC_RECEIPT_RECORD_KEYS,
  SERVICE_RECEIPT_EVENT_KEYS,
} from "../packages/receipt-authority/src/model";

const root = resolve(process.cwd());
const sourcePath = "contracts/receipt/samurai_sushi_receipt.py";
const authorityManifestPath = "contracts/receipt/authority-manifest.json";
const buildDirectory = "contracts/receipt/build";
const artifactPath = `${buildDirectory}/samurai_sushi_receipt_v1.tz`;
const artifactJsonPath = `${buildDirectory}/samurai_sushi_receipt_v1.json`;
const storagePath = `${buildDirectory}/samurai_sushi_receipt_v1.storage.tz`;
const manifestPath = `${buildDirectory}/deployment-manifest.json`;
const bindingPath = "packages/receipt-authority/src/generated/localnet-source-binding.ts";

function sha256(bytes: Uint8Array | string): string {
  return createHash("sha256").update(bytes).digest("hex");
}

function read(path: string): Buffer {
  return readFileSync(resolve(root, path));
}

function write(path: string, bytes: Uint8Array | string): void {
  const absolute = resolve(root, path);
  mkdirSync(dirname(absolute), { recursive: true });
  writeFileSync(absolute, bytes);
}

function compileSmartPy(): void {
  const python = process.env.SMARTPY_PYTHON ?? "/private/tmp/dos-esposas-smartpy/bin/python";
  const scratch = mkdtempSync(join(tmpdir(), "samurai-sushi-receipt-compile-"));
  try {
    execFileSync(python, [resolve(root, sourcePath)], { cwd: scratch, stdio: "inherit" });
    const output = join(scratch, "samurai_sushi_receipt_v1");
    mkdirSync(resolve(root, buildDirectory), { recursive: true });
    copyFileSync(join(output, "step_001_cont_0_contract.tz"), resolve(root, artifactPath));
    copyFileSync(join(output, "step_001_cont_0_contract.json"), resolve(root, artifactJsonPath));
    copyFileSync(join(output, "step_001_cont_0_storage.tz"), resolve(root, storagePath));
  } finally {
    rmSync(scratch, { recursive: true, force: true });
  }
}

function parameterSchemaHash(): string {
  const contract = JSON.parse(read(artifactJsonPath).toString("utf8")) as unknown;
  if (!Array.isArray(contract)) throw new Error("SmartPy contract artifact must be a Micheline script array.");
  const parameter = contract.find(
    (node): node is { prim: "parameter"; args: [unknown] } =>
      Boolean(node && typeof node === "object" && !Array.isArray(node) && (node as { prim?: unknown }).prim === "parameter"),
  );
  if (!parameter || !Array.isArray(parameter.args) || parameter.args.length !== 1) {
    throw new Error("SmartPy contract artifact is missing its exact parameter schema.");
  }
  return sha256CanonicalJson(parameter.args[0]);
}

compileSmartPy();

const manifest = parseSourceCandidateDeploymentManifest({
  version: 1,
  schemaVersion: 1,
  kind: "samurai-sushi-receipt-source-candidate-v1",
  consumer: "samurai-sushi",
  chainId: RECEIPT_AUTHORITY_MANIFEST.chainId,
  profile: "localnet",
  deploymentClaim: "source-only-not-originated",
  contractName: RECEIPT_AUTHORITY_MANIFEST.contractName,
  entrypoint: RECEIPT_AUTHORITY_MANIFEST.entrypoint,
  authorityManifestPath,
  authorityManifestHash: RECEIPT_AUTHORITY_MANIFEST_HASH,
  source: { path: sourcePath, sha256: sha256(read(sourcePath)) },
  artifact: {
    path: artifactPath,
    sha256: sha256(read(artifactPath)),
    storagePath,
    storageSha256: sha256(read(storagePath)),
    parameterSchemaSha256: parameterSchemaHash(),
  },
  generatedBindingPath: bindingPath,
  confirmationThreshold: RECEIPT_AUTHORITY_MANIFEST.confirmationThreshold,
  finalityPolicy: RECEIPT_AUTHORITY_MANIFEST.finalityPolicy,
  publicStorageKeys: PUBLIC_RECEIPT_RECORD_KEYS,
  publicEventKeys: SERVICE_RECEIPT_EVENT_KEYS,
  forbiddenContractSurface: FORBIDDEN_CONTRACT_SURFACE,
  claimBoundary: "authorized-permit-acceptance-only",
});

write(manifestPath, `${JSON.stringify(manifest, null, 2)}\n`);
const candidateManifestHash = sha256CanonicalJson(manifest);
const binding = `// Generated by scripts/build-receipt-authority.ts. Do not edit.\n`
  + `export const LOCALNET_RECEIPT_SOURCE_BINDING = ${JSON.stringify({
    version: 1,
    deploymentClaim: "source-only-not-originated",
    candidateManifestPath: manifestPath,
    candidateManifestHash,
    authorityManifestHash: RECEIPT_AUTHORITY_MANIFEST_HASH,
    chainId: RECEIPT_AUTHORITY_MANIFEST.chainId,
    profile: RECEIPT_AUTHORITY_MANIFEST.profile,
    contractName: RECEIPT_AUTHORITY_MANIFEST.contractName,
    entrypoint: RECEIPT_AUTHORITY_MANIFEST.entrypoint,
    contractAddress: null,
    originationOperation: null,
    artifactSha256: manifest.artifact.sha256,
    parameterSchemaSha256: manifest.artifact.parameterSchemaSha256,
  }, null, 2)} as const;\n`;
write(bindingPath, binding);

console.log(
  JSON.stringify({
    authorityManifestHash: RECEIPT_AUTHORITY_MANIFEST_HASH,
    candidateManifestHash,
    sourceSha256: manifest.source.sha256,
    artifactSha256: manifest.artifact.sha256,
    storageSha256: manifest.artifact.storageSha256,
    parameterSchemaSha256: manifest.artifact.parameterSchemaSha256,
    manifestPath: relative(root, resolve(root, manifestPath)),
    deploymentClaim: manifest.deploymentClaim,
    canonicalManifestBytes: Buffer.byteLength(canonicalJson(manifest)),
  }),
);
