import { writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { firstEveningServiceSource } from "../packages/content/src/index.ts";

const definition = firstEveningServiceSource.serviceDefinition;
const dimensions = Object.fromEntries(firstEveningServiceSource.artRequirements.map((asset) => {
  const match = /^(\d+)x(\d+)$/.exec(asset.dimensions);
  if (!match) throw new Error(`Invalid browser asset dimensions: ${asset.key}`);
  return [asset.key, [Number(match[1]), Number(match[2])]];
}));
const steps = Object.fromEntries(definition.orders.map((order) => [order.id, order.steps.map((step) => step.id)]));
const prompts = Object.fromEntries([
  [definition.startPromptRef, "service.start"],
  ...definition.riceBeats.map((beat) => [definition.ricePromptRefs[beat], "service.prepare-rice"]),
  ...definition.orders.flatMap((order) => [
    [order.acceptPromptRef, "service.accept-order"],
    ...order.steps.map((step) => [step.promptRef, "service.perform-step"]),
    [order.platePromptRef, "service.plate-order"],
    [`prompt.serve.${order.id}`, "service.serve-order"],
  ]),
  ["prompt.presentation.choose", "service.choose-presentation"],
  [definition.closePromptRef, "service.close-ledger"],
  [definition.restorationPromptRef, "service.choose-restoration"],
]);
const source = `/* Generated by scripts/generate-first-service-browser-inventory.ts. Do not edit. */
export const FIRST_SERVICE_BROWSER_INVENTORY = Object.freeze(${JSON.stringify({
  contentVersion: firstEveningServiceSource.contentVersion,
  reviewIds: firstEveningServiceSource.reviewReferences,
  copyRefs: firstEveningServiceSource.copy.map((entry) => entry.key),
  copy: Object.fromEntries(firstEveningServiceSource.copy.map((entry) => [entry.key, { text: entry.text, reviewId: entry.reviewId, reviewStatus: entry.status }])),
  assetDimensions: dimensions,
  assets: Object.fromEntries(firstEveningServiceSource.artRequirements.map((asset) => [asset.key, {
    path: `/service-assets/first-service.svg#${asset.key}`,
    width: dimensions[asset.key]![0],
    height: dimensions[asset.key]![1],
    nonColorIdentity: asset.nonColorIdentity,
    reviewId: asset.reviewId,
    reviewStatus: "review-pending",
  }])),
  sceneAnchors: {
    "counter-lamp-lit": [232, 12],
    "restoration-counter-stool": [24, 100],
    "restoration-display-shelf": [128, 76],
    "restoration-menu-board": [224, 72],
  },
  orderStatusRefs: ["order-state.offered", "order-state.accepted", "order-state.preparing", "order-state.ready-to-plate", "order-state.plated", "order-state.served", "order-state.discarded"],
  orderIds: definition.orders.map((order) => order.id),
  orderBindings: Object.fromEntries(definition.orders.map((order) => [order.id, { guestRef: `guest.${order.guestRole}`, dishRef: `dish.${order.dishId}` }])),
  commandNames: ["service.start", "service.prepare-rice", "service.accept-order", "service.perform-step", "service.choose-presentation", "service.plate-order", "service.serve-order", "service.close-ledger", "service.choose-restoration", "service.abandon"],
  riceBeats: definition.riceBeats,
  presentationChoices: definition.presentationChoices,
  restorationChoices: definition.restorationChoices,
  steps,
  promptCommands: prompts,
}, null, 2)} as const);
`;
await writeFile(resolve("apps/web/app/service-browser-inventory.generated.ts"), source, "utf8");
