import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { attestFirstServiceSprite } from "../packages/content/src/asset-attestation.ts";
import { firstEveningServiceSource } from "../packages/content/src/service.ts";

const spritePath = resolve("apps/web/public/service-assets/first-service.svg");
const source = await readFile(spritePath, "utf8");
const attestation = attestFirstServiceSprite(source, firstEveningServiceSource.artRequirements);
await writeFile(resolve("packages/content/src/browser-assets-attestation.generated.ts"),
  `/* Generated by scripts/generate-first-service-asset-attestation.ts. Do not edit. */\nexport const FIRST_SERVICE_SPRITE_ATTESTATION = Object.freeze(${JSON.stringify(attestation, null, 2)} as const);\n`, "utf8");
