import { writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import {
  buildBrowserEveningServiceView,
  compiledFirstEveningService,
  firstEveningServiceSource,
} from "../packages/content/src/index.ts";
import { projectEveningService, type EveningServiceCheckpoint } from "../packages/domain/src/evening-service.ts";

const definition = firstEveningServiceSource.serviceDefinition;
const dimensions = Object.fromEntries(firstEveningServiceSource.artRequirements.map((asset) => {
  const match = /^(\d+)x(\d+)$/.exec(asset.dimensions);
  if (!match) throw new Error(`Invalid browser asset dimensions: ${asset.key}`);
  return [asset.key, [Number(match[1]), Number(match[2])]];
}));
const steps = Object.fromEntries(definition.orders.map((order) => [order.id, order.steps.map((step) => step.id)]));
const prompts = Object.fromEntries([
  [definition.startPromptRef, "service.start"],
  [definition.abandonedPromptRef, "service.start-new"],
  ...definition.riceBeats.map((beat) => [definition.ricePromptRefs[beat], "service.prepare-rice"]),
  ...definition.orders.flatMap((order) => [
    [order.acceptPromptRef, "service.accept-order"],
    ...order.steps.map((step) => [step.promptRef, "service.perform-step"]),
    [order.platePromptRef, "service.plate-order"],
    [`prompt.serve.${order.id}`, "service.serve-order"],
  ]),
  ["prompt.presentation.choose", "service.choose-presentation"],
  [definition.closePromptRef, "service.close-ledger"],
  [definition.restorationPromptRef, "service.choose-restoration"],
]);
const checkpointOf = (entry: unknown): EveningServiceCheckpoint => {
  if (entry && typeof entry === "object" && "response" in entry) {
    return (entry as { readonly response: { readonly checkpoint: EveningServiceCheckpoint } }).response.checkpoint;
  }
  return entry as EveningServiceCheckpoint;
};
const representativeCheckpoints = [
  ...compiledFirstEveningService.goldenReplay.map(checkpointOf),
  checkpointOf(compiledFirstEveningService.abandonmentReplay.at(-1)),
  checkpointOf(compiledFirstEveningService.newRunReplay.at(-1)),
];
const promptViews = Object.fromEntries(representativeCheckpoints.map((checkpoint) => {
  const projection = projectEveningService(checkpoint, compiledFirstEveningService.projectionManifest,
    { disposition: "query", correctiveCueId: null });
  const view = buildBrowserEveningServiceView(checkpoint, projection, "guest");
  return [view.prompt.ref, {
    phase: view.phase,
    choices: view.choices.map((choice) => ({
      id: choice.id,
      labelRef: choice.label.ref,
      actionLabelRef: choice.actionLabel.ref,
      commandName: choice.commandName,
      payload: choice.payload,
      assetKey: choice.asset?.key ?? null,
    })),
    facts: view.facts.map((fact) => fact.ref),
    orders: view.orders.map((order) => ({
      orderId: order.orderId,
      statusRef: order.status.ref,
      stepIndex: order.stepIndex,
      stepTotal: order.stepTotal,
      active: order.active,
      portraitKey: order.portrait.key,
      dishAssetKey: order.dishAsset.key,
    })),
    ledgerOrderIds: view.ledgerRows.map((row) => row.orderId),
    sceneKey: view.scene.key,
    sceneLayers: view.sceneLayers.map((layer) => ({ assetKey: layer.asset.key, x: layer.x, y: layer.y })),
    restorationKey: view.restoration?.key ?? null,
    unlockKey: view.unlock.key,
  }];
}));
const source = `/* Generated by scripts/generate-first-service-browser-inventory.ts. Do not edit. */
export const FIRST_SERVICE_BROWSER_INVENTORY = Object.freeze(${JSON.stringify({
  contentVersion: firstEveningServiceSource.contentVersion,
  reviewIds: firstEveningServiceSource.reviewReferences,
  copyRefs: firstEveningServiceSource.copy.map((entry) => entry.key),
  copy: Object.fromEntries(firstEveningServiceSource.copy.map((entry) => [entry.key, { text: entry.text, reviewId: entry.reviewId, reviewStatus: entry.status }])),
  assetDimensions: dimensions,
  assets: Object.fromEntries(firstEveningServiceSource.artRequirements.map((asset) => [asset.key, {
    path: `/service-assets/first-service.svg#${asset.key}`,
    width: dimensions[asset.key]![0],
    height: dimensions[asset.key]![1],
    nonColorIdentity: asset.nonColorIdentity,
    reviewId: asset.reviewId,
    reviewStatus: "review-pending",
  }])),
  sceneAnchors: {
    "counter-lamp-lit": [232, 12],
    "restoration-counter-stool": [24, 100],
    "restoration-display-shelf": [128, 76],
    "restoration-menu-board": [224, 72],
  },
  orderStatusRefs: ["order-state.offered", "order-state.accepted", "order-state.preparing", "order-state.ready-to-plate", "order-state.plated", "order-state.served", "order-state.discarded"],
  orderIds: definition.orders.map((order) => order.id),
  orderBindings: Object.fromEntries(definition.orders.map((order) => [order.id, { guestRef: `guest.${order.guestRole}`, dishRef: `dish.${order.dishId}` }])),
  ledgerBindings: Object.fromEntries(definition.orders.map((order) => [order.id, {
    guestRef: `guest.${order.guestRole}`,
    dishRef: `dish.${order.dishId}`,
    outcomeRef: `outcome.${order.outcomeClass}`,
    plateFeedbackRef: order.plateFeedbackRef,
    serveFeedbackRef: order.serveFeedbackRef,
    storyFlagRef: `story-flag.${order.storyFlagId}`,
    consequenceRef: order.persistentConsequenceRef,
  }])),
  commandNames: ["service.start", "service.start-new", "service.prepare-rice", "service.accept-order", "service.perform-step", "service.choose-presentation", "service.plate-order", "service.serve-order", "service.close-ledger", "service.choose-restoration", "service.abandon"],
  riceBeats: definition.riceBeats,
  presentationChoices: definition.presentationChoices,
  restorationChoices: definition.restorationChoices,
  steps,
  promptCommands: prompts,
  promptViews,
}, null, 2)} as const);
`;
await writeFile(resolve("apps/web/app/service-browser-inventory.generated.ts"), source, "utf8");
